// GCP setup
const PROJECT_ID = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX';
const OAUTH_CLIENT_ID = 'XXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXXXXXXXXXXXXX.XXX';
const OAUTH_CLIENT_SECRET = 'XX_XX_XXXXXXXXXXXXXXXXXX';

// Thermostat ids
const DEVICES = [{ 
  'id': 'XXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXX_XXXX_X-XXXXXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'location': 'Living Room'
}];

// we need a sheet to stick the logs in
const LOG_SHEET_NAME = 'thermostatLogs';

// openweathermap.org access 
const OWM_API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
const OWM_LOCATION_ID = '6324729';
const OWM_UNITS = 'metric';
